# Generated by Django 5.2.5 on 2025-09-13 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_enable_pg_trgm"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="user",
            name="accounts_us_first_n_8f83ff_idx",
        ),
        migrations.RemoveIndex(
            model_name="user",
            name="accounts_us_last_na_2d3d8e_idx",
        ),
        migrations.RemoveIndex(
            model_name="user",
            name="accounts_us_email_3c6f6d_idx",
        ),
        migrations.RemoveIndex(
            model_name="user",
            name="accounts_us_first_n_0a8d8e_idx",
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="avatar",
            field=models.ImageField(
                blank=True,
                help_text="Upload a profile picture (max 5MB, JPG/PNG/WEBP)",
                null=True,
                upload_to="avatars/%Y/%m/%d/",
            ),
        ),
    ]
