# Generated by Django 5.2.5 on 2025-09-07 11:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="rental_type",
            field=models.CharField(
                choices=[
                    ("full_property", "Full Property"),
                    ("rooms_only", "Rooms Only"),
                    ("both", "Both Full Property and Rooms"),
                ],
                default="full_property",
                help_text="Specify if the property is rented as a whole or by rooms",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="area_sqft",
            field=models.PositiveIntegerField(help_text="Total area in square feet"),
        ),
        migrations.AlterField(
            model_name="property",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Base price for full property rental",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="utilities_included",
            field=models.BooleanField(
                default=False,
                help_text="If checked, utilities are included in the room prices",
            ),
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "room_type",
                    models.CharField(
                        choices=[
                            ("single", "Single Room"),
                            ("selfcon", "Self-Contained"),
                            ("room_toilet", "Room & Toilet"),
                            ("room_kitchen", "Room & Kitchen"),
                            ("shared_room", "Shared Room"),
                        ],
                        default="single",
                        max_length=20,
                    ),
                ),
                (
                    "room_number",
                    models.CharField(
                        help_text="Room number or identifier", max_length=20
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "area_sqft",
                    models.PositiveIntegerField(help_text="Room area in square feet"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("occupied", "Occupied"),
                            ("maintenance", "Under Maintenance"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("has_bathroom", models.BooleanField(default=False)),
                ("has_kitchen", models.BooleanField(default=False)),
                ("has_balcony", models.BooleanField(default=False)),
                ("has_ac", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rooms",
                        to="rooms.property",
                    ),
                ),
            ],
            options={
                "ordering": ["room_number"],
                "unique_together": {("property", "room_number")},
            },
        ),
    ]
